namespace ZemisApi.Core.Models.Enums
{
    public enum LoanProviderType
    {
        CREDIT7 = 1,
        CREDIT_PLUS = 2,
        MY_CREDIT = 3,
        SHVIDKO_GROSHI = 4,
        DINERO = 5,
        E_GROSHI = 6,
        TENGO = 7,
        CCLOAN = 8,
        CASH_BERRY = 9,
        ALEX_CREDIT = 10,
        MONEYVEO = 11,
        MILOAN = 12,
        BISTRO_ZAYM = 13,
        VASHA_GOTIVOCHKA = 14,
        FORZA_CREDIT = 15,
        SOS_CREDIT = 16,
        CREDIT_KASSA = 17,
        ZECREDIT = 18,
        KACHAY_GROSHI = 19,
        MONEY4YOU = 20,
        LOANY = 21,
        KF_UA = 22,
        CREDIT_BOX = 23,
        POZICHKA = 24,
        MONEY_BOOM = 25,
        NEOCREDIT = 26,
        BANANA_CREDIT = 27,
        EVRO_GROSHI = 28,
        MONETKA = 29,
    }
}