// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZemisApi.Infrastructure.DataAccess;

namespace ZemisApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210617220752_AddLoansAndSeo")]
    partial class AddLoansAndSeo
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "6.0.0-preview.4.21253.1");

            modelBuilder.Entity("ZemisApi.Core.Models.Loan", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("AmountFrom")
                        .HasColumnType("int");

                    b.Property<int>("AmountTo")
                        .HasColumnType("int");

                    b.Property<string>("BonusesDescription")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<int>("BorrowerAgeFrom")
                        .HasMaxLength(120)
                        .HasColumnType("int");

                    b.Property<int>("BorrowerAgeTo")
                        .HasMaxLength(120)
                        .HasColumnType("int");

                    b.Property<string>("CommissionDescription")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<double>("DayRate")
                        .HasColumnType("double");

                    b.Property<string>("ExtraInfo")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<double>("InitialDayRate")
                        .HasColumnType("double");

                    b.Property<bool>("IsOnlineProcessing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("IssueWorkingHoursDescription")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("ProcessingTimeMinutes")
                        .HasMaxLength(10080)
                        .HasColumnType("int");

                    b.Property<string>("ReceiversDescription")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("RepaymentMethodsDescription")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.Property<int>("TermDays")
                        .HasMaxLength(43200)
                        .HasColumnType("int");

                    b.Property<string>("WithdrawalMethodsDescription")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar(1500)");

                    b.HasKey("Id");

                    b.ToTable("Loan");
                });

            modelBuilder.Entity("ZemisApi.Core.Models.Seo", b =>
                {
                    b.Property<string>("Url")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Description")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Keywords")
                        .HasMaxLength(180)
                        .HasColumnType("varchar(180)");

                    b.Property<string>("Title")
                        .HasMaxLength(80)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Url");

                    b.ToTable("Seo");
                });
#pragma warning restore 612, 618
        }
    }
}
