# This is a basic workflow to help you get started with Actions

name: Deploy all components

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-all:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/production.key
          chmod 600 ~/.ssh/production.key
          cat >>~/.ssh/config <<END
          Host production
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/production.key
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}

      - name: Clonning or pulling
        run: |
          ssh production /bin/bash -s << EOT
          cd /home/
          if [ ! -d ./zemis ]
          then
          git clone $CLONE_URL
          else
          cd ./zemis
          git fetch && git reset --hard origin/master
          fi 
          EOT
        env:
          CLONE_URL: ${{ secrets.CLONE_URL }}

      - name: Deploy application
        run: ssh production 'cd /home/zemis/ && bash deploy-all.sh'
